/** What happened. Values are persisted, so treat them as an append-only list. */
export enum AuditAction {
  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',
  DELIVERY_APPROVED = 'DELIVERY_APPROVED',
  DELIVERY_REJECTED = 'DELIVERY_REJECTED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  PARCEL_CREATED = 'PARCEL_CREATED',
  PARCEL_CANCELLED = 'PARCEL_CANCELLED',
  PARCEL_DELIVERY_CONFIRMED = 'PARCEL_DELIVERY_CONFIRMED',
  PARCEL_PROOF_SUBMITTED = 'PARCEL_PROOF_SUBMITTED',
  PARCEL_BLOCKED = 'PARCEL_BLOCKED',
  PARCEL_UNBLOCKED = 'PARCEL_UNBLOCKED',
  PARCEL_ASSIGNED = 'PARCEL_ASSIGNED',
  PARCEL_UNASSIGNED = 'PARCEL_UNASSIGNED',
  PARCEL_STATUS_CHANGED = 'PARCEL_STATUS_CHANGED',
}

export enum AuditTargetType {
  USER = 'USER',
  PARCEL = 'PARCEL',
}
